import TopNavBar from "@/components/navbar/topnavbar";
import SearchBar from "@/components/searchbar/searchbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "test",
  description: "Generated by create next app",
};

export default function RoomCardsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-full w-full flex flex-col">
      <div className="flex flex-col h-[10%] gap-2 w-full">
        <TopNavBar />
      </div>
      <div className=" flex w-full flex-1 overflow-y-auto">{children}</div>
    </div>
  );
}
