import BackButton from "@/components/button/backbutton";
import TopNavBar from "@/components/navbar/topnavbar";
import SearchBar from "@/components/searchbar/searchbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "test",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-full w-full">
      {/* <BackButton /> */}
      <div className="h-full flex bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-gray-100 to-[#003C43] justify-center items-center">
        {children}
      </div>
    </div>
  );
}
