import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster} from "sonner";
// import Provider from "@/query-client/provider";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children?: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session} basePath="/api/auth">
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-center" richColors />
        <div className="w-full h-full">
          {children}
        </div>
      </body>
    </html>
    </SessionProvider>
  );
}
